"""add slack_installation table

Revision ID: e15156ef9971
Revises: 
Create Date: 2026-09-03 18:32:40.544305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15156ef9971'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=32), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.EncryptedString(length=1024), nullable=False),
    sa.Column('refresh_token', sa.EncryptedString(length=1024), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.String(length=1024), nullable=False),
    sa.Column('bot_user_id', sa.String(length=32), nullable=True),
    sa.Column('needs_reauth', sa.Boolean(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_slack_installations_team_id'), 'slack_installations', ['team_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slack_installations_team_id'), table_name='slack_installations')
    op.drop_table('slack_installations')
    # ### end Alembic commands ###
